---
title: "Corona Virus Report"
author:
- familyname: XXXX
  othernames: XXX
  address: Monash Universtidy
  email: XXX
  correspondingauthor: true
  qualifications:  XXX
- familyname: XXXX
  othernames: Reports
  address: XXX
  qualifications: XXX
- familyname: XXX
  othernames: XXX
  address: XXX
  email: XXX
  correspondingauthor: true
  qualifications:  XXX
department: Our consultancy \newline add names &\newline add names
organization: Australian Government COVID19
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  bookdown::pdf_document2:
    template: monashreport2.tex
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
---

```{r , echo = FALSE, message = FALSE, warning = FALSE}
# Libraries

library(tidyverse)
library(readr)
library(kableExtra)
library(bookdown)

```

```{r}
#Loading dataset

wwc <- read_csv("data/worldwidecases.csv")
```

\section*{Country XX1 and YY1"}

\section*{Country XX2 and YY2}

\section*{Country XX3 and YY3}

Filter the dataset to present the countries of interest: 
  - France
  - Sweden
```{r filter-countries}
france_and_sweden <- wwc %>%
  filter(countriesAndTerritories %in% c("France", "Sweden"))
         
```

Figure for countries
```{r glimpse-of-countries}
glimpse(france_and_sweden)
```

Table for France
```{r table-france}
table_france <- France %>%
  select(dateRep, cases, deaths) %>%
  arrange(desc(deaths)) %>%
  kable(caption = "Table showing the dates with higest number of confirmed cases and deaths for France") %>%
  kable_styling(bootstrap_options = c("hover", "striped"))
table_france
```



Plot the cases by dateRep
```{r table-sweden-deaths-cases}
table_sweden <- Sweden %>% 
  select(dateRep, cases, deaths) %>%
  arrange(desc(deaths)) %>%
  kable(caption = "Table showing the dates with higest number of confirmed cases and deaths for Sweden") %>%
  kable_styling(bootstrap_options = c("hover", "striped"))
table_sweden
```

Plot most 


